Initializing joining channels
CFC-Servers/cfc_voice_channels pull request #11
Opened 2019-03-26 20:53 UTC by OverlordBleck

My working PR for joining channels

2019-03-26 21:38 UTC, OverlordBleck commented
Oof I made a mistake, going in and fixing it

2019-03-26 21:49 UTC, OverlordBleck commented
Works flawlessly now! =^)

2019-03-26 22:06 UTC, sarahsturgeon requested changes
quick feedback, will look at it more later

2019-03-26 22:06 UTC, brandonsturgeon commented on lua/cfc_voice_channels/core/sv/sv_channel_control.lua
> +        ["TrimedName"] = string.lower(string.Trim(channelName)),
Trimmed*

2019-03-26 22:06 UTC, brandonsturgeon commented on lua/cfc_voice_channels/core/sv/sv_channel_control.lua
> +    return nil
No need for a return here

2019-03-26 22:16 UTC, OverlordBleck commented on lua/cfc_voice_channels/core/sv/sv_channel_control.lua
> +        ["TrimedName"] = string.lower(string.Trim(channelName)),
Oof can’t spell

2019-03-26 22:31 UTC, ajs5710 commented on lua/cfc_voice_channels/core/sv/sv_channel_control.lua
> +        if channel.TrimedName == string.lower(string.Trim(name)) then
Here too

2019-03-26 22:31 UTC, ajs5710 commented on lua/cfc_voice_channels/core/sv/sv_channel_control.lua
> +        if channel.TrimedName == string.lower(string.Trim(channelName)) then
At least your spelling is consistant

2019-03-26 22:38 UTC, OverlordBleck commented on lua/cfc_voice_channels/core/sv/sv_channel_control.lua
> +        if channel.TrimedName == string.lower(string.Trim(channelName)) then
Copy and paste is a bitch

2019-03-27 03:55 UTC, sarahsturgeon approved these changes
LGTM as long as you're planning on doing a final cleanup sweep

2019-03-27 04:02 UTC, merged